name: Greetings

on: 
  pull_request_target:
    types: [opened, closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      if: github.event.action == 'opened'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "🎉 Welcome to your first pull request on the sticky-memo repository! The Wisdom Fox community appreciates your contribution and can't wait to review your work. If you need any assistance or clarification, don’t hesitate to ask. Thanks for helping us improve sticky-memo!"

    - name: Merge Success Message
      if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"body": "✅ Thank you for your contribution! You're now part of the Wisdom Fox family. Happy contributing! 🎉"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
